#for Job class
NOTIFICATION_TIMEOUT = 604800
KILL_JOB_DEFAULT_TIMEOUT = 1209600


#Packet`s names policy
PCK_DUPLICATE_NAME_IGNORE = 0b001
PCK_DUPLICATE_NAME_WARNING = 0b010
PCK_DUPLICATE_NAME_EXCEPTION = 0b100
DEFAULT_PCK_DUPLICATE_NAME_POLICY = PCK_DUPLICATE_NAME_EXCEPTION